In [43]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

What is neuron and what is neural network?

nerual network is the computational model developed by the taking inspiration from biological neural network. This consist of layers and nodes in it
these nodes are called neurons


In [44]:
def load_coffee_data():
    """ Creates a coffee roasting data set.
        roasting duration: 12-15 minutes is best
        temperature range: 175-260C is best
    """
    rng = np.random.default_rng(2)
    X = rng.random(400).reshape(-1,2)
    X[:,1] = X[:,1] * 4 + 11.5          # 12-15 min is best
    X[:,0] = X[:,0] * (285-150) + 150  # 350-500 F (175-260 C) is best
    Y = np.zeros(len(X))
    
    i=0
    for t,d in X:
        y = -3/(260-175)*t + 21
        if (t > 175 and t < 260 and d > 12 and d < 15 and d<=y ):
            Y[i] = 1
        else:
            Y[i] = 0
        i += 1

    return (X, Y.reshape(-1,1))


In [62]:
X,y=load_coffee_data()
print(X[:5],y[:5])
# here i am not utilizing any dataset we have numpy vector data
X.shape,y.shape

[[185.31763812  12.69396457]
 [259.92047498  11.86766377]
 [231.01357101  14.41424211]
 [175.3666449   11.72058651]
 [187.12086467  14.12973206]] [[1.]
 [0.]
 [0.]
 [0.]
 [1.]]


((200, 2), (200, 1))

In [46]:
# we need to normalize the values of data for that we will use keras normalizer
norm_1 = tf.keras.layers.Normalization(axis=1)
norm_1.adapt(X)
X_n = norm_1(X)
print(X_n[:5])

tf.Tensor(
[[-0.8345548 -0.6528792]
 [ 1.0323056 -1.3851453]
 [ 0.3089395  0.8716251]
 [-1.0835686 -1.5154841]
 [-0.7894309  0.6194935]], shape=(5, 2), dtype=float32)


In [55]:
# will use tenserflow for creating our NN of single perceptron with fpp
tf.random.set_seed(1234)
model=Sequential(
    [
        tf.keras.Input(shape=(2,)),
        Dense(3,activation='sigmoid',name='layer1'),
        Dense(1,activation='sigmoid',name='layer2'),
        
    ]
    
)

In [56]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                  │ (None, 3)              │             9 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer2 (Dense)                  │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13 (52.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

In [57]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(),
             optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
)

In [58]:
w1,b1=model.get_layer('layer1').get_weights()
w2,b2=model.get_layer('layer2').get_weights()
w1,b1,w2,b2

(array([[ 0.934916  ,  0.5739584 , -1.0247763 ],
        [ 0.7871276 ,  0.9689987 ,  0.76165164]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[ 0.66350436],
        [-0.4745379 ],
        [-0.3678816 ]], dtype=float32),
 array([0.], dtype=float32))

In [59]:
model.fit(Xn,y,epochs=10
         
         )

Epoch 1/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.6662  
Epoch 2/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6122 
Epoch 3/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5688 
Epoch 4/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5357 
Epoch 5/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5118 
Epoch 6/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4951 
Epoch 7/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4836 
Epoch 8/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4756 
Epoch 9/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4696 
Epoch 10/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4648 


In [64]:
X_test = np.array([
    [185.3,12.6],  # postive example
    [200,17]])   # negative example
X_testn = norm_1(X_test)
predictions = model.predict(X_testn)
print("predictions = \n", predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
predictions = 
 [[0.30081326]
 [0.11204628]]


In [65]:
yhat = np.zeros_like(predictions)
for i in range(len(predictions)):
  if predictions[i] >= 0.5:
    yhat[i] = 1
  else:
    yhat[i] = 0
print(f"decisions = \n {yhat}")

decisions = 
 [[0.]
 [0.]]
